package com.mycompany.mavenproject1;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.*;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class RestaurantGui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RestaurantGui.class.getName());

    /**
     * Creates new form RestaurantGui
     */
    public RestaurantGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultsFrame = new javax.swing.JFrame();
        resultScroll = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        menuTabPane = new javax.swing.JTabbedPane();
        customersPanel = new javax.swing.JPanel();
        customersScroll = new javax.swing.JScrollPane();
        customersTable = new javax.swing.JTable();
        showCustBtn = new javax.swing.JButton();
        clearCustBtn = new javax.swing.JButton();
        updateCustBtn = new javax.swing.JButton();
        addCustBtn = new javax.swing.JButton();
        custNameField = new javax.swing.JTextField();
        custPhoneField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deleteCustBtn = new javax.swing.JButton();
        employeesPanel = new javax.swing.JPanel();
        employeesScroll = new javax.swing.JScrollPane();
        employeesTable = new javax.swing.JTable();
        showEmpBtn = new javax.swing.JButton();
        clearEmpBtn = new javax.swing.JButton();
        updateEmpBtn = new javax.swing.JButton();
        addEmpBtn = new javax.swing.JButton();
        deleteEmpBtn = new javax.swing.JButton();
        empNameField = new javax.swing.JTextField();
        empRoleField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        orderPanel = new javax.swing.JPanel();
        orderScroll = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        showOrderBtn = new javax.swing.JButton();
        clearOrdBtn = new javax.swing.JButton();
        addOrderBtn = new javax.swing.JButton();
        updateOrderBtn = new javax.swing.JButton();
        deleteOrderBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        orderStatusCombo = new javax.swing.JComboBox<>();
        menuPanel = new javax.swing.JPanel();
        menuScroll = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        showMenuBtn = new javax.swing.JButton();
        clearMenuBtn = new javax.swing.JButton();
        updateMenuBtn = new javax.swing.JButton();
        addMenuBtn = new javax.swing.JButton();
        deleteMenuBtn = new javax.swing.JButton();
        menuNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        menuCategoryField = new javax.swing.JTextField();
        menuPriceField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        reservationPanel = new javax.swing.JPanel();
        reservationScroll = new javax.swing.JScrollPane();
        reservationTable = new javax.swing.JTable();
        showResBtn = new javax.swing.JButton();
        clearResBtn = new javax.swing.JButton();
        updateResBtn = new javax.swing.JButton();
        addResBtn = new javax.swing.JButton();
        deleteResBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        resStatusCombo = new javax.swing.JComboBox<>();

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        resultScroll.setViewportView(resultTable);

        javax.swing.GroupLayout resultsFrameLayout = new javax.swing.GroupLayout(resultsFrame.getContentPane());
        resultsFrame.getContentPane().setLayout(resultsFrameLayout);
        resultsFrameLayout.setHorizontalGroup(
            resultsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
            .addGroup(resultsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(resultsFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(resultScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        resultsFrameLayout.setVerticalGroup(
            resultsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
            .addGroup(resultsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(resultsFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(resultScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        customersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customersTableMouseClicked(evt);
            }
        });
        customersScroll.setViewportView(customersTable);

        showCustBtn.setText("Show");
        showCustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCustBtnActionPerformed(evt);
            }
        });

        clearCustBtn.setText("Clear");
        clearCustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCustBtnActionPerformed(evt);
            }
        });

        updateCustBtn.setText("Update");
        updateCustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustBtnActionPerformed(evt);
            }
        });

        addCustBtn.setText("Add");
        addCustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Phone");

        deleteCustBtn.setText("Delete");
        deleteCustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customersPanelLayout = new javax.swing.GroupLayout(customersPanel);
        customersPanel.setLayout(customersPanelLayout);
        customersPanelLayout.setHorizontalGroup(
            customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customersPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(customersPanelLayout.createSequentialGroup()
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showCustBtn)
                            .addComponent(clearCustBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customersPanelLayout.createSequentialGroup()
                                .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(custNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(custPhoneField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customersPanelLayout.createSequentialGroup()
                                .addComponent(addCustBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(updateCustBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteCustBtn))))
                    .addComponent(customersScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        customersPanelLayout.setVerticalGroup(
            customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(customersPanelLayout.createSequentialGroup()
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCustBtn)
                            .addComponent(updateCustBtn)
                            .addComponent(deleteCustBtn)))
                    .addGroup(customersPanelLayout.createSequentialGroup()
                        .addComponent(showCustBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearCustBtn)))
                .addGap(18, 18, 18)
                .addComponent(customersScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        menuTabPane.addTab("Customers", customersPanel);

        employeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        employeesScroll.setViewportView(employeesTable);

        showEmpBtn.setText("Show");
        showEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEmpBtnActionPerformed(evt);
            }
        });

        clearEmpBtn.setText("Clear");
        clearEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEmpBtnActionPerformed(evt);
            }
        });

        updateEmpBtn.setText("Update");

        addEmpBtn.setText("Add");

        deleteEmpBtn.setText("Delete");

        jLabel3.setText("Name");

        jLabel4.setText("Role");

        javax.swing.GroupLayout employeesPanelLayout = new javax.swing.GroupLayout(employeesPanel);
        employeesPanel.setLayout(employeesPanelLayout);
        employeesPanelLayout.setHorizontalGroup(
            employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeesPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(employeesScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(employeesPanelLayout.createSequentialGroup()
                        .addGroup(employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showEmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearEmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeesPanelLayout.createSequentialGroup()
                                .addComponent(addEmpBtn)
                                .addGap(12, 12, 12)
                                .addComponent(updateEmpBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteEmpBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeesPanelLayout.createSequentialGroup()
                                .addGroup(employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(empNameField)
                                    .addComponent(empRoleField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(12, 12, 12))
        );
        employeesPanelLayout.setVerticalGroup(
            employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeesPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showEmpBtn)
                    .addGroup(employeesPanelLayout.createSequentialGroup()
                        .addGroup(employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empRoleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEmpBtn)
                    .addComponent(updateEmpBtn)
                    .addComponent(deleteEmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearEmpBtn))
                .addGap(18, 18, 18)
                .addComponent(employeesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        menuTabPane.addTab("Employees", employeesPanel);

        orderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTableMouseClicked(evt);
            }
        });
        orderScroll.setViewportView(orderTable);

        showOrderBtn.setText("Show");
        showOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOrderBtnActionPerformed(evt);
            }
        });

        clearOrdBtn.setText("Clear");
        clearOrdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearOrdBtnActionPerformed(evt);
            }
        });

        addOrderBtn.setText("Add");

        updateOrderBtn.setText("Update");

        deleteOrderBtn.setText("Delete");

        jLabel5.setText("Status");

        orderStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showOrderBtn)
                            .addComponent(clearOrdBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(addOrderBtn)
                                .addGap(15, 15, 15)
                                .addComponent(updateOrderBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(orderStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12))
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(showOrderBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearOrdBtn))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(orderStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteOrderBtn)
                            .addComponent(updateOrderBtn)
                            .addComponent(addOrderBtn))))
                .addGap(18, 18, 18)
                .addComponent(orderScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        menuTabPane.addTab("Orders", orderPanel);

        menuScroll.setViewportView(menuTable);

        showMenuBtn.setText("Show");
        showMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMenuBtnActionPerformed(evt);
            }
        });

        clearMenuBtn.setText("Clear");
        clearMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMenuBtnActionPerformed(evt);
            }
        });

        updateMenuBtn.setText("Update");

        addMenuBtn.setText("Add");

        deleteMenuBtn.setText("Delete");

        jLabel6.setText("Name");

        jLabel7.setText("Category");

        jLabel8.setText("Price");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showMenuBtn)
                            .addComponent(clearMenuBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                .addComponent(addMenuBtn)
                                .addGap(15, 15, 15)
                                .addComponent(updateMenuBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteMenuBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(menuNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(menuCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(menuPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(menuScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menuNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menuCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menuPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteMenuBtn)
                            .addComponent(updateMenuBtn)
                            .addComponent(addMenuBtn)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(showMenuBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearMenuBtn)))
                .addGap(18, 18, 18)
                .addComponent(menuScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        menuTabPane.addTab("Menu", menuPanel);

        reservationScroll.setViewportView(reservationTable);

        showResBtn.setText("Show");
        showResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showResBtnActionPerformed(evt);
            }
        });

        clearResBtn.setText("Clear");
        clearResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearResBtnActionPerformed(evt);
            }
        });

        updateResBtn.setText("Update");

        addResBtn.setText("Add");

        deleteResBtn.setText("Delete");

        jLabel9.setText("Status");

        resStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout reservationPanelLayout = new javax.swing.GroupLayout(reservationPanel);
        reservationPanel.setLayout(reservationPanelLayout);
        reservationPanelLayout.setHorizontalGroup(
            reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservationPanelLayout.createSequentialGroup()
                        .addGroup(reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showResBtn)
                            .addComponent(clearResBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reservationPanelLayout.createSequentialGroup()
                                .addComponent(addResBtn)
                                .addGap(15, 15, 15)
                                .addComponent(updateResBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteResBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reservationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(resStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(reservationScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        reservationPanelLayout.setVerticalGroup(
            reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showResBtn)
                    .addComponent(jLabel9)
                    .addComponent(resStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearResBtn)
                    .addGroup(reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateResBtn)
                        .addComponent(deleteResBtn)
                        .addComponent(addResBtn)))
                .addGap(18, 18, 18)
                .addComponent(reservationScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        menuTabPane.addTab("Reservations", reservationPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuTabPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuTabPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearResBtnActionPerformed
        reservationTable.setModel(new DefaultTableModel());
    }//GEN-LAST:event_clearResBtnActionPerformed

    private void showResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showResBtnActionPerformed
        reservationTable.setModel(rDao.getAllReservations(connection));
    }//GEN-LAST:event_showResBtnActionPerformed

    private void clearMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMenuBtnActionPerformed
        menuTable.setModel(new DefaultTableModel());
    }//GEN-LAST:event_clearMenuBtnActionPerformed

    private void showMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMenuBtnActionPerformed
        menuTable.setModel(mDao.getAllMenuItems(connection));
    }//GEN-LAST:event_showMenuBtnActionPerformed

    private void clearOrdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearOrdBtnActionPerformed
        orderTable.setModel(new DefaultTableModel());
    }//GEN-LAST:event_clearOrdBtnActionPerformed

    private void showOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOrderBtnActionPerformed
        orderTable.setModel(oDao.getAllOrders(connection));
    }//GEN-LAST:event_showOrderBtnActionPerformed

    private void orderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTableMouseClicked
        if (evt.getClickCount() == 2) { // double-click
            int row = orderTable.getSelectedRow();
            if (row != -1) {
                int orderId = Integer.parseInt(orderTable.getValueAt(row, 0).toString());
                showOrderItemsDialog(orderId);
            }
        }
    }//GEN-LAST:event_orderTableMouseClicked

    private void clearEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEmpBtnActionPerformed
        employeesTable.setModel(new DefaultTableModel());
    }//GEN-LAST:event_clearEmpBtnActionPerformed

    private void showEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEmpBtnActionPerformed
        employeesTable.setModel(eDao.getAllEmployees(connection));
    }//GEN-LAST:event_showEmpBtnActionPerformed

    private void deleteCustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustBtnActionPerformed
        if(selectedCustId == -1){
            JOptionPane.showMessageDialog(this, "No customer selected!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this customer?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
        );
        if(confirm == JOptionPane.YES_OPTION){
            cDao.deleteCustomer(connection, selectedCustId);
            customersTable.setModel(cDao.getAllCustomers(connection));
            selectedCustId = -1;
        }else
        JOptionPane.showMessageDialog(this, "Error: Customer ID not found in database!", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_deleteCustBtnActionPerformed

    private void addCustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustBtnActionPerformed
        String username = custNameField.getText();
        String phone = custPhoneField.getText();
        custNameField.setText("");
        custPhoneField.setText("");
        cDao.addCustomer(connection, username, phone);
        customersTable.setModel(cDao.getAllCustomers(connection));
    }//GEN-LAST:event_addCustBtnActionPerformed

    private void updateCustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustBtnActionPerformed
        if(selectedCustId == -1){
            JOptionPane.showMessageDialog(this, "No customer selected!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to update this customer?",
            "Confirm Update",
            JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            String username = custNameField.getText();
            String phone = custPhoneField.getText();
            custNameField.setText("");
            custPhoneField.setText("");
            cDao.updateCustomer(connection, selectedCustId, username, phone);
            customersTable.setModel(cDao.getAllCustomers(connection));
            selectedCustId = -1;
        }else
        JOptionPane.showMessageDialog(this, "Error: Customer ID not found in database!", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_updateCustBtnActionPerformed

    private void clearCustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCustBtnActionPerformed
        customersTable.setModel(new DefaultTableModel());
    }//GEN-LAST:event_clearCustBtnActionPerformed

    private void showCustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCustBtnActionPerformed
        customersTable.setModel(cDao.getAllCustomers(connection));
    }//GEN-LAST:event_showCustBtnActionPerformed

    private void customersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersTableMouseClicked
        if (evt.getClickCount() == 2) {
            int row = customersTable.getSelectedRow();
            if (row != -1) {
                selectedCustId = Integer.parseInt(customersTable.getValueAt(row, 0).toString());
                String custName = customersTable.getValueAt(row, 1).toString();
                String custPhone = customersTable.getValueAt(row, 2).toString();
                custNameField.setText(custName);
                custPhoneField.setText(custPhone);
            }
        }
    }//GEN-LAST:event_customersTableMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try{
            DatabaseManager.connect();
            connection = DatabaseManager.getConnection();
            
            Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                System.out.println("JVM shutting down, closing DB...");
                DatabaseManager.close();
            }));

        }catch(SQLException ex){
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
		System.out.println("Message: " + ex.getMessage());
		ex = ex.getNextException();
            }
        }
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(() -> new RestaurantGui().setVisible(true));
        
        
    }
    
    private void showOrderItemsDialog(int orderId) {
        // Create dialog
        JDialog dialog = new JDialog((JFrame) SwingUtilities.getWindowAncestor(this), "Order #" + orderId + " Items", true);
        dialog.setSize(500, 300);
        dialog.setLocationRelativeTo(this);

        // Create table
        dialog.add(resultScroll, BorderLayout.CENTER);  

        // Fetch data from DAO
        OrderDao dao = new OrderDao();
        DefaultTableModel model = dao.getOrderItems(connection, orderId);
        resultTable.setModel(model);

        dialog.setVisible(true);
    }


    CustomerDao cDao = new CustomerDao();
    EmployeeDao eDao = new EmployeeDao();
    OrderDao oDao = new OrderDao();
    MenuDao mDao = new MenuDao();
    ReservationDao rDao = new ReservationDao();
    static Connection connection = null;
    private int selectedCustId = -1;
    private int selectedOrderId = -1;
    private int selectedMenuId = -1;
    private int selectedEmpId = -1;
    private int selectedResId = -1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustBtn;
    private javax.swing.JButton addEmpBtn;
    private javax.swing.JButton addMenuBtn;
    private javax.swing.JButton addOrderBtn;
    private javax.swing.JButton addResBtn;
    private javax.swing.JButton clearCustBtn;
    private javax.swing.JButton clearEmpBtn;
    private javax.swing.JButton clearMenuBtn;
    private javax.swing.JButton clearOrdBtn;
    private javax.swing.JButton clearResBtn;
    private javax.swing.JTextField custNameField;
    private javax.swing.JTextField custPhoneField;
    private javax.swing.JPanel customersPanel;
    private javax.swing.JScrollPane customersScroll;
    private javax.swing.JTable customersTable;
    private javax.swing.JButton deleteCustBtn;
    private javax.swing.JButton deleteEmpBtn;
    private javax.swing.JButton deleteMenuBtn;
    private javax.swing.JButton deleteOrderBtn;
    private javax.swing.JButton deleteResBtn;
    private javax.swing.JTextField empNameField;
    private javax.swing.JTextField empRoleField;
    private javax.swing.JPanel employeesPanel;
    private javax.swing.JScrollPane employeesScroll;
    private javax.swing.JTable employeesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField menuCategoryField;
    private javax.swing.JTextField menuNameField;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField menuPriceField;
    private javax.swing.JScrollPane menuScroll;
    private javax.swing.JTabbedPane menuTabPane;
    private javax.swing.JTable menuTable;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JScrollPane orderScroll;
    private javax.swing.JComboBox<String> orderStatusCombo;
    private javax.swing.JTable orderTable;
    private javax.swing.JComboBox<String> resStatusCombo;
    private javax.swing.JPanel reservationPanel;
    private javax.swing.JScrollPane reservationScroll;
    private javax.swing.JTable reservationTable;
    private javax.swing.JScrollPane resultScroll;
    private javax.swing.JTable resultTable;
    private javax.swing.JFrame resultsFrame;
    private javax.swing.JButton showCustBtn;
    private javax.swing.JButton showEmpBtn;
    private javax.swing.JButton showMenuBtn;
    private javax.swing.JButton showOrderBtn;
    private javax.swing.JButton showResBtn;
    private javax.swing.JButton updateCustBtn;
    private javax.swing.JButton updateEmpBtn;
    private javax.swing.JButton updateMenuBtn;
    private javax.swing.JButton updateOrderBtn;
    private javax.swing.JButton updateResBtn;
    // End of variables declaration//GEN-END:variables
    }
